
datadump.location:
  author: src/main/resources/test-authors.txt
  works: src/main/resources/test-works.txt

spring:
  application:
    name: betterreads-data-loader

  #    name: inbox-app
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: Iv1.c3e45e5991da6530
#            client-secret: a4b3d4ce451372391782086ab575c44549d95347
  data:
    cassandra:
      keyspace-name: main
      username: QdUIuTPPRYCuOZQxwTvgJaXM
      password: LE1WnbwUvJQNZLsY62CXMbPFNTvRxMH,J6R0OkgsrwK7FB4Mxt,byFZNwC3sklxs2s+qvUaO67aScDDgrEJhQXFTqbGWmoNLBva3QDUuqc1tOZpcXUZTFiM6,mT0Yu+u
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s




datastax.astra:
    secure-connect-bundle: secure-connect-betterreads.zip


astra:
   db:
    id: a83980f1-b080-4d86-b9e3-d42b0104a95a-1
    region: europe-west1
    keyspace: main
    application.token: AstraCS:QdUIuTPPRYCuOZQxwTvgJaXM:3092d986c3b5863e06e52411f9036b7d377050296cc12490d116864c34a261a3






